### ISSUE TITLE
Formatting on jira and message in api.js

### ISSUE THREAD

**Issue by MarcinDadura** [aexol-studio/bddx#23]
**103 line in api.js**

example of desired task created in bddx
![obraz](https://user-images.githubusercontent.com/75130735/227552720-6b073ebd-dcee-43a3-9af7-2f4a280962e0.png)

**Comment by AleksanderBondar** [comment]
@MarcinDadura https://github.com/aexol-studio/bddx/tree/27.03.23/fixes
